# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=36, verbose_name='公司名')),
                ('number', models.CharField(max_length=11, verbose_name='企业编号')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
            ],
        ),
        migrations.CreateModel(
            name='Limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=18, verbose_name='权限描述')),
                ('limit', models.CharField(max_length=3, verbose_name='权限标识')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=18, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='用户密码')),
                ('is_active', models.BooleanField(default=1, verbose_name='是否启用')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
                ('limits', models.ManyToManyField(to='user.Limits')),
            ],
        ),
    ]
