# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_order', models.CharField(max_length=18, verbose_name='主单号')),
                ('order_number', models.CharField(max_length=18, verbose_name='订单号')),
                ('shipper', models.CharField(max_length=18, verbose_name='发货人')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('weight', models.FloatField(default=0, verbose_name='重量')),
                ('volume', models.FloatField(default=0, verbose_name='体积')),
                ('city', models.CharField(max_length=9, verbose_name='城市')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remarks', models.CharField(max_length=512, verbose_name='备注')),
                ('consignee', models.CharField(max_length=18, verbose_name='收货人')),
                ('tel', models.CharField(max_length=36, verbose_name='联系方式')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=18, verbose_name='状态名')),
                ('state', models.CharField(max_length=3, verbose_name='状态标识')),
            ],
        ),
        migrations.AddField(
            model_name='order_state',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.State'),
        ),
    ]
