# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-04 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='p_order',
        ),
    ]
